# Generated by Django 5.2.1 on 2025-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('discount', models.FloatField()),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('bogo', 'Buy-One-Get-One-Free'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
