# Generated by Django 5.2.1 on 2025-06-23 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_list_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='slug',
        ),
    ]
